services:
  db:
    container_name: sql-server25
    image: mcr.microsoft.com/mssql/server:2025-RC0-ubuntu-24.04
    environment:
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
    volumes:
      - sql-vol:/var/opt/mssql
  redis:
    container_name: redis-local
    image: redis:latest
    depends_on:
      - db
  api:
    container_name: apiredis-api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "5150:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=OrderDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
      - ConnectionStrings_RedisConnection=redis
    depends_on:
      - db
      - redis
volumes:
  sql-vol:
      external: true